import '../app/data/models/product_model.dart';
import 'constants.dart';

class DummyHelper {
  const DummyHelper._();

  static List<String> sales = [
    "T Shirt      Size: M",
    "T Shirt      Size: S",
    "T Shirt      Size: L",
    "T Shirt      Size: M",
    "T Shirt      Size: L",
    "T Shirt      Size: L",
    "T Shirt      Size: S",
    "T Shirt      Size: M",
    "T Shirt      Size: L",
    "T Shirt      Size: M",
    "T Shirt      Size: S",
    "T Shirt      Size: L",
    "T Shirt      Size: M",
    "T Shirt      Size: L",
    "T Shirt      Size: L",
    "T Shirt      Size: S",
    "T Shirt      Size: M",
    "T Shirt      Size: L",
  ];

  static List<ProductModel> products = [
    ProductModel(
      id: 1,
      image: 'assets/images/no-bg0.png',
      name: 'Metro Man Tees',
      username: 'PriyaP3tal27',
      quantity: 0,
      price: 449,
      rating: 4.6,
      reviews: '1.5k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 2,
      image: 'assets/images/no-bg1.png',
      name: 'Gritty Guy Gear',
      username: 'RaHulRhythms8',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.1k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 3,
      image: 'assets/images/no-bg2.png',
      name: 'Urban Edge Ts',
      username: '45AishaAmber',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 4,
      image: 'assets/images/no-bg3.png',
      name: 'Nomad Noir Tops',
      username: 'V1kramVoyag3r73',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 5,
      image: 'assets/images/no-bg4.png',
      name: 'Rebel Roar Shirts',
      username: 'AniKa1chemy92',
      quantity: 0,
      price: 449,
      rating: 4.3,
      reviews: '1.1k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 6,
      image: 'assets/images/no-bg5.png',
      name: 'Classic Cool Tees',
      username: '12ArjunAstral',
      quantity: 0,
      price: 449,
      rating: 4.6,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 7,
      image: 'assets/images/no-bg6.png',
      name: 'Tech Tribe Ts',
      username: 'M33raMystique56',
      quantity: 0,
      price: 449,
      rating: 4.9,
      reviews: '2.0k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 8,
      image: 'assets/images/no-bg7.png',
      name: 'Vintage Vibe Wear',
      username: 'RoHanR3nd3zv0us9',
      quantity: 0,
      price: 449,
      rating: 4.2,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 9,
      image: 'assets/images/no-bg8.png',
      name: 'Urban Zen Tops',
      username: 'NishaN3bula31',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.7k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 10,
      image: 'assets/images/no-bg9.png',
      name: 'Maverick Mode Ts',
      username: 'K4birK4leido77',
      quantity: 0,
      price: 449,
      rating: 4.6,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 11,
      image: 'assets/images/no-bg10.png',
      name: 'Street Swagger Gear',
      username: 'DeepaDazzle4',
      quantity: 0,
      price: 449,
      rating: 4.1,
      reviews: '1.2k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 12,
      image: 'assets/images/no-bg11.png',
      name: 'Bold Bloom Tees',
      username: 'SiddharthSerene65',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.2k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 13,
      image: 'assets/images/no-bg12.png',
      name: 'Coastal Chill Tops',
      username: 'MayaMelody2',
      quantity: 0,
      price: 449,
      rating: 4.7,
      reviews: '1.7k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 14,
      image: 'assets/images/no-bg13.png',
      name: 'Alpha Aura Shirts',
      username: 'Kar4nKismet51',
      quantity: 0,
      price: 449,
      rating: 4.4,
      reviews: '1.7k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 15,
      image: 'assets/images/no-bg14.png',
      name: 'Retro Rumble Ts',
      username: 'Pooj4Pinnacle99',
      quantity: 0,
      price: 449,
      rating: 4.1,
      reviews: '1.5k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 16,
      image: 'assets/images/no-bg15.png',
      name: 'Dapper Dose Wear',
      username: 'AshishAurora23',
      quantity: 0,
      price: 449,
      rating: 4.1,
      reviews: '1.2k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 17,
      image: 'assets/images/no-bg16.png',
      name: 'Mystic Muse Ts',
      username: 'SnehaSt3llar76',
      quantity: 0,
      price: 449,
      rating: 4.4,
      reviews: '1.3k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 18,
      image: 'assets/images/no-bg17.png',
      name: 'Slick Style Tops',
      username: 'VivekVort3x44',
      quantity: 0,
      price: 449,
      rating: 4.1,
      reviews: '1.2k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 19,
      image: 'assets/images/no-bg18.png',
      name: 'Dynamic Dusk Tees',
      username: 'Nat4shaNova12',
      quantity: 0,
      price: 449,
      rating: 4.4,
      reviews: '1.1k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 20,
      image: 'assets/images/no-bg19.png',
      name: 'Modern Mojo Gear',
      username: 'RajivRapture87',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.0k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 21,
      image: 'assets/images/no-bg20.png',
      name: 'Rugged Rhythm Ts',
      username: '7AnanyaAegis33',
      quantity: 0,
      price: 449,
      rating: 4.3,
      reviews: '1.1k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 22,
      image: 'assets/images/no-bg21.png',
      name: 'Rogue Realm Tops',
      username: 'Pr4navPanorama55',
      quantity: 0,
      price: 449,
      rating: 4.6,
      reviews: '1.7k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 23,
      image: 'assets/images/no-bg22.png',
      name: 'Grit & Grace Tees',
      username: 'RituRhythm21',
      quantity: 0,
      price: 449,
      rating: 4.5,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 24,
      image: 'assets/images/no-bg23.png',
      name: 'Varsity Vogue Ts',
      username: '2ArnavAstral9',
      quantity: 0,
      price: 449,
      rating: 4.5,
      reviews: '1.1k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 25,
      image: 'assets/images/no-bg24.png',
      name: 'Nomad Noir Gear',
      username: 'Diy4Delight78',
      quantity: 0,
      price: 449,
      rating: 4.3,
      reviews: '1.6k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 26,
      image: 'assets/images/no-bg25.png',
      name: 'Titan Thread Tops',
      username: '6AdityaAether64',
      quantity: 0,
      price: 449,
      rating: 4.3,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 27,
      image: 'assets/images/no-bg26.png',
      name: 'Noir Nectar Tees',
      username: 'NainaNebu1a87',
      quantity: 0,
      price: 449,
      rating: 4.2,
      reviews: '1.7k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 28,
      image: 'assets/images/no-bg27.png',
      name: 'Stealth Street Ts',
      username: '5SameerSpectrum',
      quantity: 0,
      price: 449,
      rating: 4.0,
      reviews: '1.2k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 29,
      image: 'assets/images/no-bg28.png',
      name: 'Tech Titan Tops',
      username: '11AyeshaAstral22',
      quantity: 0,
      price: 449,
      rating: 4.3,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 30,
      image: 'assets/images/no-bg29.png',
      name: 'Venture Vibe Tees',
      username: 'VarunVibr4nce67',
      quantity: 0,
      price: 449,
      rating: 4.7,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 31,
      image: 'assets/images/no-bg30.png',
      name: 'Titan Threads Gear',
      username: 'Z4hidZephyr',
      quantity: 0,
      price: 449,
      rating: 4.3,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 32,
      image: 'assets/images/no-bg31.png',
      name: 'Metro Maverick Ts',
      username: 'ShrutiS3nse89',
      quantity: 0,
      price: 449,
      rating: 4.5,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 33,
      image: 'assets/images/no-bg32.png',
      name: 'Street Slick Tops',
      username: 'DeviDynamic27',
      quantity: 0,
      price: 449,
      rating: 5.0,
      reviews: '1.0k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 34,
      image: 'assets/images/no-bg33.png',
      name: 'Zenith Zone Tees',
      username: 'V1manVoyager',
      quantity: 0,
      price: 449,
      rating: 4.9,
      reviews: '1.7k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 35,
      image: 'assets/images/no-bg34.png',
      name: 'Urban Utopia Ts',
      username: 'AaravApex45',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.6k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 36,
      image: 'assets/images/no-bg35.png',
      name: 'Noir Nomad Tops',
      username: 'RiyaRhapsody76',
      quantity: 0,
      price: 449,
      rating: 4.7,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 37,
      image: 'assets/images/no-bg36.png',
      name: 'Daring Dusk Tees',
      username: 'JaiJubilant21',
      quantity: 0,
      price: 449,
      rating: 4.7,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 38,
      image: 'assets/images/no-bg37.png',
      name: 'Precision Pace Gear',
      username: 'KaavyaKaleido',
      quantity: 0,
      price: 449,
      rating: 4.1,
      reviews: '1.5k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 39,
      image: 'assets/images/no-bg38.png',
      name: 'City Sleek Ts',
      username: '3VihanVerve',
      quantity: 0,
      price: 449,
      rating: 4.5,
      reviews: '1.6k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 40,
      image: 'assets/images/no-bg39.png',
      name: 'Rebel Realm Tops',
      username: 'SaanviSeraphic',
      quantity: 0,
      price: 449,
      rating: 4.6,
      reviews: '1.9k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 41,
      image: 'assets/images/no-bg40.png',
      name: 'Fusion Force Tees',
      username: 'VihaanVibrant',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.3k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 42,
      image: 'assets/images/no-bg41.png',
      name: 'Blaze Bold Wear',
      username: 'ZaraZenith',
      quantity: 0,
      price: 449,
      rating: 4.9,
      reviews: '1.5k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 43,
      image: 'assets/images/no-bg42.png',
      name: 'Verve Vortex Ts',
      username: '8KaviKaleido',
      quantity: 0,
      price: 449,
      rating: 4.8,
      reviews: '1.1k reviews',
      size: 'M',
      isFavorite: false,
    ),

    ProductModel(
      id: 44,
      image: 'assets/images/no-bg43.png',
      name: 'Nocturnal Nexus Top',
      username: 'TanyaTuneless',
      quantity: 0,
      price: 449,
      rating: 4.0,
      reviews: '1.8k reviews',
      size: 'M',
      isFavorite: false,
    ),
  ]..shuffle();
}